// <auto-generated />
using System;
using AspireDemo.Data.Analytics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspireDemo.Data.Analytics.Migrations;

[DbContext(typeof(AnalyticsDbContext))]
[Migration("20250101000001_InitialAnalytics")]
partial class InitialAnalytics
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.1")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("AspireDemo.Data.Analytics.PageView", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

            b.Property<string>("IpAddress")
                .HasColumnType("text");

            b.Property<string>("Path")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<DateTime>("Timestamp")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("UserAgent")
                .HasMaxLength(1000)
                .HasColumnType("character varying(1000)");

            b.HasKey("Id");

            b.HasIndex("Timestamp");

            b.ToTable("PageViews");
        });

        modelBuilder.Entity("AspireDemo.Data.Analytics.UserEvent", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

            b.Property<string>("EventName")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            b.Property<string>("Properties")
                .HasColumnType("jsonb");

            b.Property<DateTime>("Timestamp")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("UserId")
                .HasColumnType("text");

            b.HasKey("Id");

            b.HasIndex("EventName", "Timestamp");

            b.ToTable("UserEvents");
        });
#pragma warning restore 612, 618
    }
}
